name: Homer Build

on:
  push:
    branches:
      - sucicada

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}


      #      - name: init
#        run: |
#          apt update && apt install -y rsync
#      - name: Get config
#        run: git submodule update --init --recursive

      - name: Build project
        run: |
          ln config/config.yml public/assets/config.yml
          npm install -g yarn
          yarn install
          yarn build

      - name: ssh-scp-deploy
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: ./dist/                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: ${{secrets.DEPLOY_PATH}}/                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.SSH_HOST}}                                      # Remote server address - REQUIRED true
          #          port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.SSH_USERNAME}}                                      # Remote server user - REQUIRED true
          password: ${{secrets.SSH_PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key"
          ssh_options: -o StrictHostKeyChecking=no

#      - name: Sync files to remote server
#        uses: burnett01/rsync-deployments@5.2.1
#        with:
#          switches: -avzr
#          path: dist/
#          remote_path: /${{ secrets.DEPLOY_PATH }}
#          remote_host: ${{ secrets.SSH_HOST }}
#          remote_user: ${{ secrets.SSH_USERNAME }}
#          remote_key: ${{ secrets.SSH_KEY }}
#
#        env:
#          ssh_host: ${{ secrets.ssh_host }}
#          ssh_passw  ord: ${{ secrets.ssh_password }}
#          ssh_username: ${{ secrets.ssh_username }}
#          deploy_path: ${{ secrets.deploy_path }}
#        run: |
#          rsync -avz --delete ./dist/ ${{env.ssh_username}}@${{env.ssh_host}}:${{env.deploy_path}} --password-file=<(echo "${{env.ssh_password}}")
#

      - name: Webhook
        if: always()
        uses: SuCicada/su-action-webhook@latest
        with:
          url: ${{secrets.WEBHOOK_URL}}
          job: ${{toJSON(job)}}
          github: ${{toJSON(github)}}
